name: CitySkylines
version: ${project.version}
main: de.marvinleiers.cityskylines.CitySkylines
api-version: 1.13
authors: [Marvin2k0]
website: www.marvinleiers.de
commands:
  city:
    permission: cs.city
    aliases: [cityskylines, cs]
